events {}

http {
        upstream shield_api {
        server 172.17.0.1:8080;  # твой Shield API на хосте
    }

    upstream backend_service {
        server 172.17.0.1:8081;  # твой Backend сервис на хосте
    }

    server {
        listen 80;

        location /api/ {
            auth_request /shield-check;

            proxy_pass http://backend_service;
        }

        location = /shield-check {
            internal;

            proxy_pass http://shield_api/decision;

            proxy_pass_request_body on;
            proxy_set_header Content-Type application/json;

            # передача метаданных
            proxy_set_header X-Client-IP $remote_addr;
            proxy_set_header X-Endpoint $uri;
        }
    }
}