rate:
  limit:
    window: 60
    limit: 100000
    endpoints:
      "[api/ping]":
        limit: 5
        window: 60
      "[api/reports]":
        limit: 2
        window: 120
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer